---
name: Linting (YAML)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      # only run when yaml files are updated
    paths:
      - "**.yml"

jobs:
  yamllint:
    name: Run yamllint against YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                max: 120
                level: warning
